### PR TITLE
Follow redirects in Excon everywhere

### LINKED ISSUE #4: Exception when version not present in Python manifest
We've had an error via Sentry from bump:

```
JSON::ParserError: 765: unexpected token at ''
  from json/common.rb:156:in `parse'
  from json/common.rb:156:in `parse'
  from bump/update_checkers/python.rb:12:in `latest_version'
  from bump/update_checkers/base.rb:16:in `needs_update?'
  from /app/app/workers/dependency_updater.rb:62:in `update_dependency!'
  from /app/app/workers/dependency_updater.rb:33:in `perform'
```

It comes from here:
```ruby
        @latest_version ||=
          begin
            url = "https://pypi.python.org/pypi/#{dependency.name}/json"
            JSON.parse(Excon.get(url).body)["info"]["version"]
          end
      end
```

```ruby
# job args
{
  dependency: {'language': 'python', 'version': '1.0.13', 'name': 'sqlalchemy', 'previous_version': nil}, 
  dependency_files: [Filtered], 
  repo: {'commit': 'ca4cd6230ce6abcxxxxx24e42d89cfad6df3ffbb', 'name': 'gocardless/xxxx', 'language': 'python'}
}
```

I'm guessing that Excon.get(..) is returning an empty response, as `https://pypi.python.org/pypi/SQLAlchemy/json` includes this metadata?

### PR DESCRIPTION
**Pull request by greysteil**
Fixes #4.

### CODE REVIEW

File: lib/bump/update_checkers/python.rb [hunk 1]
```diff
@@ -1,15 +1,20 @@
...
         @latest_version ||=
           begin
-            url = "https://pypi.python.org/pypi/#{dependency.name}/json"
-            JSON.parse(Excon.get(url).body)["info"]["version"]
+            pypi_response = Excon.get(
+              dependency_url,
+              middlewares: SharedHelpers.excon_middleware
+            )
+
+            JSON.parse(pypi_response.body)["info"]["version"]
```
Comment (nickcampbell18) [inline lib/bump/update_checkers/python.rb:17]: This is better, but still explodes if the response JSON is malformed/empty. Should we maybe add some failure handling around that case as well? Could use something like Ruby 2.3's `Hash#dig` as a possibility?

File: lib/bump/shared_helpers.rb [hunk 2]
```diff
@@ -50,5 +50,9 @@ def self.in_a_forked_process
       return result unless result.is_a?(Hash) && result[:_error_details]
       raise ChildProcessFailed, result[:_error_details]
     end
+
+    def self.excon_middleware
+      Excon.defaults[:middlewares] + [Excon::Middleware::RedirectFollower]
```
Comment (nickcampbell18) [inline lib/bump/shared_helpers.rb:56]: It's probably in the load path by this point, but would be good to have an explicit `require excon/middleware/redirect_follower` at the top of the file?

**Review by nickcampbell18 — APPROVED** [review]
A couple of suggestions, but otherwise good 👍

File: lib/bump/shared_helpers.rb (hunk 2 above)
Comment (greysteil) [reply lib/bump/shared_helpers.rb:56]: Good shout. I think requiring `excon` should be enough - will add that in.

File: lib/bump/update_checkers/python.rb (hunk 1 above)
Comment (greysteil) [reply lib/bump/update_checkers/python.rb:17]: Yeah, I was surprised the existing code didn't handle that. Have you not been receiving sentries about it?

Comment (greysteil) [reply lib/bump/update_checkers/python.rb:17]: Hmmm, just had a look through the code and Python and Node are both lacking any kind of "this dependency actually exists" check.

I could use `dig` above, but I think it would be better to put a separate PR in to check existence explicitly. Then, if the dependency exists but we get some malformed stuff back from PyPi / NPM, we probably *do* want to explode.

Comment (nickcampbell18) [reply lib/bump/update_checkers/python.rb:17]: 👍 for a separate PR, I think that would add a nice bit of robustness!

**Comment by nickcampbell18** [comment]
👍
